apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo1-deployment
  labels:
    app: mongo1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo1
  template:
    metadata:
      labels:
        app: mongo1
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret1
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret1
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service1
spec:
  selector:
    app: mongo1
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27018
